# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20170304_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_parsed',
            field=models.BooleanField(default=False),
        ),
    ]
