# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 01:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20170304_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correlation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlation', models.FloatField(default=0)),
                ('book_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book1_corr', to='books.Book')),
                ('book_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book2_corr', to='books.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Euclidean',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('euclidean', models.FloatField(default=0)),
                ('book_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book1_euc', to='books.Book')),
                ('book_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book2_euc', to='books.Book')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='correlation_sim',
            field=models.ManyToManyField(related_name='correlation_of', through='books.Correlation', to='books.Book'),
        ),
        migrations.AddField(
            model_name='book',
            name='euclidian_sim',
            field=models.ManyToManyField(related_name='euclidean_of', through='books.Euclidean', to='books.Book'),
        ),
    ]
