# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20170311_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='correlation_sim',
            field=models.ManyToManyField(related_name='correlation_of', through='books.Correlation', to='books.Book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='euclidian_sim',
            field=models.ManyToManyField(related_name='euclidean_of', through='books.Euclidean', to='books.Book'),
        ),
    ]
