# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 04:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_auto_20170311_0351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='correlation',
            old_name='correlation',
            new_name='book_correlation',
        ),
        migrations.RenameField(
            model_name='euclidean',
            old_name='euclidean',
            new_name='book_distance',
        ),
        migrations.AlterField(
            model_name='correlation',
            name='book_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book1_corr+', to='books.Book'),
        ),
        migrations.AlterField(
            model_name='correlation',
            name='book_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book2_corr+', to='books.Book'),
        ),
        migrations.AlterField(
            model_name='euclidean',
            name='book_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book1_euc+', to='books.Book'),
        ),
        migrations.AlterField(
            model_name='euclidean',
            name='book_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book2_euc+', to='books.Book'),
        ),
    ]
