# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 15:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_auto_20170311_0453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='correlation',
            old_name='book_correlation',
            new_name='distance',
        ),
        migrations.RenameField(
            model_name='euclidean',
            old_name='book_distance',
            new_name='distance',
        ),
    ]
