# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 05:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_auto_20170311_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DistanceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='correlation_sim',
        ),
        migrations.RemoveField(
            model_name='book',
            name='euclidian_sim',
        ),
        migrations.AddField(
            model_name='distance',
            name='book_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book1_distance+', to='books.Book'),
        ),
        migrations.AddField(
            model_name='distance',
            name='book_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book2_distance+', to='books.Book'),
        ),
        migrations.AddField(
            model_name='distance',
            name='distance_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.DistanceType'),
        ),
        migrations.AddField(
            model_name='book',
            name='distance',
            field=models.ManyToManyField(related_name='distance_to', through='books.Distance', to='books.Book'),
        ),
    ]
