# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 06:05
from __future__ import unicode_literals

from django.db import migrations

COSINE='cosine'
EUCLIDEAN='euclidean'
PEARSON='pearson'
JACCARD='jaccard'
DICE='dice'

NEW_DISTANCE_TYPES = [
    COSINE,
    EUCLIDEAN,
    PEARSON,
    JACCARD,
    DICE,
]

def create_distance_types(apps, schema_editor):
    DistanceType = apps.get_model('books', 'DistanceType')
    DistanceType.objects.all().delete()
    for distance_type in NEW_DISTANCE_TYPES:
        DistanceType.objects.create(
            name=distance_type,
            code=distance_type,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_auto_20170312_0558'),
    ]

    operations = [
        migrations.RunPython(create_distance_types)
    ]
