# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 21:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_auto_20170312_0605'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='distance',
            unique_together=set([('book_1', 'book_2', 'distance_type')]),
        ),
        migrations.AlterUniqueTogether(
            name='posting',
            unique_together=set([('book', 'token')]),
        ),
    ]
