# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-30 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_auto_20170530_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrating',
            name='rating',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
