# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-31 00:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_bookrating_rating'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookrating',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='bookrating',
            name='book',
        ),
        migrations.RemoveField(
            model_name='bookrating',
            name='user',
        ),
        migrations.DeleteModel(
            name='BookRating',
        ),
    ]
