# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-31 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0020_bookrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('df', models.PositiveIntegerField(default=0)),
                ('total_occurances', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='has_word_vector',
            field=models.BooleanField(default=False),
        ),
    ]
