# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-31 03:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0021_auto_20170531_0303'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordPosting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tf', models.PositiveIntegerField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Word')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='wordposting',
            unique_together=set([('book', 'word')]),
        ),
    ]
