# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-31 03:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0022_auto_20170531_0312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('compound', models.FloatField(default=0)),
                ('pos', models.FloatField(default=0)),
                ('neg', models.FloatField(default=0)),
                ('neu', models.FloatField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book')),
            ],
        ),
    ]
